# 参考
# https://github.com/qiubaiying/qiubaiying.github.io/wiki/%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA%E8%AF%A6%E7%BB%86%E6%95%99%E7%A8%8B

# Site settings
# 基础设置
title: 藏经阁
SEOTitle: 陈国林 | 玄苦 | 藏经阁
header-img: img/home-bg-o.jpg
email: cgl1079743846@gmail.com
description: "贫僧法号玄苦: ①写过Golang、C++、Python、Java、Ruby ②熟悉Linux、K8s、Docker ③会写一些前端 ④了解一些搜索引擎、大数据、区块链方面知识"
keyword: "佛曰：万发缘生，皆系缘分"
url: "https://chenguolin.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/chenguolin/chenguolin.github.io.git" # you code repository

# Sidebar settings
# 侧边栏
sidebar: true                                 # whether or not using Sidebar.
sidebar-about-description: "贫僧法号玄苦: ①写过Golang、C++、Python、Java、Ruby ②熟悉Linux、K8s、Docker ③会写一些前端 ④了解一些搜索引擎、大数据、区块链方面知识"
sidebar-avatar: /img/head-img.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
# 社交账号
RSS: false
zhihu_username:     chenguolin
github_username:    chenguolin

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: xuanku
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: db030ec9e585657cb1d3                            #生成的clientID
  clientSecret: 697410ab11e55e96b6696a998b34743b274dfb17    #生成的clientSecret
  repo: chenguolin.github.io    #仓库名称
  owner: chenguolin    #github用户名
  admin: chenguolin
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


